Teacup: crc.c File Reference
crc.c File Reference
crc16 routine
#include "crc.h"
#include <util/crc16.h>
Functions
uint16_t crc_block (void *data, uint16_t len)
block-at-once CRC16 calculator
Detailed Description
crc16 routine
Function Documentation
uint16_t crc_block (void * data, uint16_t len)
block-at-once CRC16 calculator
Parameters:
*data data to find crc16 for
len length of data
Returns:
uint16 crc16 of passed data
uses avr-libc's optimised crc16 routine
Referenced by heater_init(), heater_print(), and heater_save_settings().