Teacup: sermsg.c File Reference
sermsg.c File Reference
primitives for sending numbers over the serial link
#include "sermsg.h"
#include "serial.h"
Functions
void serwrite_hex4 (uint8_t v)
write a single hex digit
void serwrite_hex8 (uint8_t v)
write a pair of hex digits
void serwrite_hex16 (uint16_t v)
write four hex digits
void serwrite_hex32 (uint32_t v)
write eight hex digits
void serwrite_uint32 (uint32_t v)
write decimal digits from a long unsigned int
void serwrite_int32 (int32_t v)
write decimal digits from a long signed int
void serwrite_uint32_vf (uint32_t v, uint8_t fp)
write decimal digits from a long unsigned int
void serwrite_int32_vf (int32_t v, uint8_t fp)
write decimal digits from a long signed int
Variables
const uint32_t powers [] = {1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000}
list of powers of ten, used for dividing down decimal numbers for sending, and also for our crude floating point algorithm
Detailed Description
primitives for sending numbers over the serial link
Function Documentation
void serwrite_hex16 (uint16_t v)
write four hex digits
Parameters:
v word to write
Referenced by sersendf_P(), and serwrite_hex32().
void serwrite_hex32 (uint32_t v)
write eight hex digits
Parameters:
v long word to write
Referenced by sersendf_P().
void serwrite_hex4 (uint8_t v)
write a single hex digit
Parameters:
v hex digit to write, higher nibble ignored
Referenced by serwrite_hex8().
void serwrite_hex8 (uint8_t v)
write a pair of hex digits
Parameters:
v byte to write. One byte gives two hex digits
Referenced by sersendf_P(), and serwrite_hex16().
void serwrite_int32 (int32_t v)
write decimal digits from a long signed int
Parameters:
v number to send
Referenced by gcode_parse_char(), and sersendf_P().
void serwrite_int32_vf (int32_t v, uint8_t fp)
write decimal digits from a long signed int
Parameters:
v number to send
Referenced by sersendf_P().
void serwrite_uint32 (uint32_t v)
write decimal digits from a long unsigned int
Parameters:
v number to send
Referenced by gcode_parse_char(), sersendf_P(), and serwrite_int32().
void serwrite_uint32_vf (uint32_t v, uint8_t fp)
write decimal digits from a long unsigned int
Parameters:
v number to send
Referenced by serwrite_int32_vf().